<?php

namespace AppBundle\Repository;

/**
 * AppTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
