<?php

namespace AppBundle\Repository;

/**
 * MediaReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
