# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt

    role_hierarchy:
        ROLE_ORGANISATION: ROLE_USER

    providers:
        our_db_provider:
          entity:
            class: AppBundle:User
            property: username

    firewalls:

        main:
          pattern: ^/
          anonymous: ~
          form_login:
            login_path: login
            check_path: login
          provider: our_db_provider
          logout:
            path: /logout
            target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authorised, role: ROLE_ORGANISATION }
        - { path: ^/accounts*, role: ROLE_USER}
