# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     app.tag_parser:
       class: AppBundle\Service\TagParser
       arguments: [ "@doctrine.orm.entity_manager" ]

     app.s3_uploader:
       class: AppBundle\Service\S3Uploader
       arguments: ["%s3_bucket%", "%s3_token%", "%s3_secret%" ]

     app.post_summariser:
       class: AppBundle\Service\PostSummariser
       arguments: ["@doctrine.orm.entity_manager", "@app.tag_parser"]

     app.twig_extension:
       class: AppBundle\Twig\AbsoluteValueExtension
       public: false
       tags:
          - { name: twig.extension }
